---
title: "PARCIAL 2"
author: "María Paula Camargo Rincón"
date: "2026-06-04"
output: html_document
---

```{r Librerias, include=FALSE}
#setwd("C:/PERSONAL_MAPU/UNIVERSIDADES/NACIONAL/ESTADÍSTICA_ESPACIAL/PARCIAL_2")
library(readxl)
library(dplyr)
library(lubridate) # para función lubridate::hour, lubridate::minute y lubridate::second
library(tidyverse)


```



```{r PM10-O3, eval=FALSE, warning=FALSE, include=FALSE}
reporte_ene_jun_2024 <- read_excel("reporteIbocaene-jun-2024.xlsx", 
    sheet = "Sheet1", range = "A5:T4350")
reporte_ene_jun_2024 <- reporte_ene_jun_2024 %>% 
  dplyr::mutate(`Fecha & Hora` = ymd_hms(`Fecha & Hora`)
  ) %>% 
  dplyr::filter(lubridate::hour(`Fecha & Hora`) == 12,
         lubridate::minute(`Fecha & Hora`) == 0,
         lubridate::second(`Fecha & Hora`) == 0)
reporte_ene_jun_2024 <- reporte_ene_jun_2024 %>% 
  dplyr::mutate(
    across(
      -`Fecha & Hora`,
      ~ na_if(.x, "Sin data")
    )
  )
reporte_ene_jun_2024 <- reporte_ene_jun_2024 %>%
  mutate(
    across(-1, as.numeric)
  )
reporteIbocajul_dic2024 <- read_excel("reporteIbocajul-dic2024.xlsx", 
    range = "A5:T3806")
reporteIbocajul_dic2024 <- reporteIbocajul_dic2024 %>% 
  dplyr::mutate(`Fecha & Hora` = ymd_hms(`Fecha & Hora`)) %>% 
  dplyr::filter(lubridate::hour(`Fecha & Hora`) == 12,
         lubridate::minute(`Fecha & Hora`) == 0,
         lubridate::second(`Fecha & Hora`) == 0)
reporteIbocajul_dic2024 <- reporteIbocajul_dic2024 %>% 
  dplyr::mutate(
    across(
      -`Fecha & Hora`,
      ~ na_if(.x, "Sin data")
    )
  )
reporteIbocajul_dic2024 <- reporteIbocajul_dic2024 %>%
  mutate(
    across(-1, as.numeric)
  )
reporteIboca <- read_excel("reporteIboca.xlsx", 
    range = "A5:T4281")
reporteIboca <- reporteIboca %>% 
  dplyr::mutate(`Fecha & Hora` = ymd_hms(`Fecha & Hora`)) %>% 
  dplyr::filter(lubridate::hour(`Fecha & Hora`) == 12,
         lubridate::minute(`Fecha & Hora`) == 0,
         lubridate::second(`Fecha & Hora`) == 0)
reporteIboca <- reporteIboca %>% 
  dplyr::mutate(
    across(
      -`Fecha & Hora`,
      ~ na_if(.x, "Sin data")
    )
  )
reporteIboca <- reporteIboca %>%
  mutate(
    across(-1, as.numeric)
  )
reporteIbocajul_dic <- read_excel("reporteIbocajul-dic.xlsx", 
    range = "A5:T4183")
reporteIbocajul_dic <- reporteIbocajul_dic %>% 
  dplyr::mutate(`Fecha & Hora` = ymd_hms(`Fecha & Hora`)) %>% 
  dplyr::filter(lubridate::hour(`Fecha & Hora`) == 12,
         lubridate::minute(`Fecha & Hora`) == 0,
         lubridate::second(`Fecha & Hora`) == 0)
reporteIbocajul_dic <- reporteIbocajul_dic %>% 
  dplyr::mutate(
    across(
      where(is.character) & -`Fecha & Hora`,
      ~ na_if(.x, "Sin data")
    )
  )
reporteIbocajul_dic <- reporteIbocajul_dic %>%
  mutate(
    across(-1, as.numeric)
  )
PM10 <- bind_rows(
  reporte_ene_jun_2024,
  reporteIbocajul_dic2024,
  reporteIboca,
  reporteIbocajul_dic
)
PM10 <- PM10 %>%
  tidyr::pivot_longer(
    cols = -`Fecha & Hora`,      # Mantener la fecha fija
    names_to = "Estacion",       # Las columnas de estaciones pasan a ser filas
    values_to = "PM10"           # Los valores van a una nueva columna llamada PM10
  )

reporte_ene_jun_2024_o <- read_excel("reporte_ene_jun_o.xlsx", 
    sheet = "Sheet1", range = "A5:T4345")
reporte_ene_jun_2024_o <- reporte_ene_jun_2024_o %>% 
  dplyr::mutate(`Fecha & Hora` = ymd_hms(`Fecha & Hora`)
  ) %>% 
  dplyr::filter(lubridate::hour(`Fecha & Hora`) == 12,
         lubridate::minute(`Fecha & Hora`) == 0,
         lubridate::second(`Fecha & Hora`) == 0)
reporte_ene_jun_2024_o <- reporte_ene_jun_2024_o %>% 
  dplyr::mutate(
    across(
      -`Fecha & Hora`,
      ~ na_if(.x, "Sin data")
    )
  )
reporte_ene_jun_2024_o <- reporte_ene_jun_2024_o %>%
  mutate(
    across(-1, as.numeric)
  )
reporteIbocajul_dic2024_o <- read_excel("reporte_jul_dic_o_2024.xlsx", 
    range = "A5:T3791")
reporteIbocajul_dic2024_o <- reporteIbocajul_dic2024_o %>% 
  dplyr::mutate(`Fecha & Hora` = ymd_hms(`Fecha & Hora`)) %>% 
  dplyr::filter(lubridate::hour(`Fecha & Hora`) == 12,
         lubridate::minute(`Fecha & Hora`) == 0,
         lubridate::second(`Fecha & Hora`) == 0)
reporteIbocajul_dic2024_o <- reporteIbocajul_dic2024_o %>% 
  dplyr::mutate(
    across(
      -`Fecha & Hora`,
      ~ na_if(.x, "Sin data")
    )
  )
reporteIbocajul_dic2024_o <- reporteIbocajul_dic2024_o %>%
  mutate(
    across(-1, as.numeric)
  )
reporte_ene_jun_o_2025 <- read_excel("reporte_ene_jun_o_2025.xlsx", 
    range = "A5:T4301")
reporte_ene_jun_o_2025 <- reporte_ene_jun_o_2025 %>% 
  dplyr::mutate(`Fecha & Hora` = ymd_hms(`Fecha & Hora`)) %>% 
  dplyr::filter(lubridate::hour(`Fecha & Hora`) == 12,
         lubridate::minute(`Fecha & Hora`) == 0,
         lubridate::second(`Fecha & Hora`) == 0)
reporte_ene_jun_o_2025 <- reporte_ene_jun_o_2025 %>% 
  dplyr::mutate(
    across(
      -`Fecha & Hora`,
      ~ na_if(.x, "Sin data")
    )
  )
reporte_ene_jun_o_2025 <- reporte_ene_jun_o_2025 %>%
  mutate(
    across(-1, as.numeric)
  )
reporteIbocajul_dic_o_2025 <- read_excel("reporte_jul_dic_o_2025.xlsx", 
    range = "A5:T4200")
reporteIbocajul_dic_o_2025 <- reporteIbocajul_dic_o_2025 %>% 
  dplyr::mutate(`Fecha & Hora` = ymd_hms(`Fecha & Hora`)) %>% 
  dplyr::filter(lubridate::hour(`Fecha & Hora`) == 12,
         lubridate::minute(`Fecha & Hora`) == 0,
         lubridate::second(`Fecha & Hora`) == 0)
reporteIbocajul_dic_o_2025 <- reporteIbocajul_dic_o_2025 %>% 
  dplyr::mutate(
    across(
      where(is.character) & -`Fecha & Hora`,
      ~ na_if(.x, "Sin data")
    )
  )
reporteIbocajul_dic_o_2025 <- reporteIbocajul_dic_o_2025 %>%
  mutate(
    across(-1, as.numeric)
  )
O3 <- bind_rows(
  reporte_ene_jun_2024_o,
  reporteIbocajul_dic2024_o,
  reporte_ene_jun_o_2025,
  reporteIbocajul_dic_o_2025
)
O3 <- O3 %>%
  tidyr::pivot_longer(
    cols = -`Fecha & Hora`,      # Mantener la fecha fija
    names_to = "Estacion",       # Las columnas de estaciones pasan a ser filas
    values_to = "O3"             # Los valores van a una nueva columna llamada O3
  )

```

```{r}
# 3. Unir ambos datasets en uno solo final
#reporte_completo <- full_join(PM10, O3, by = c("Fecha & Hora", "Estacion"))
#writexl::write_xlsx(reporte_completo,"reporte_completo.xlsx")
reporte_completo <- read_excel("reporte_completo.xlsx")
str(reporte_completo)
summary(reporte_completo)
tabla_conteos_NAS <- data.frame(
  estaciones=names(reporte_completo)[-1],
  conteos=colSums(is.na(reporte_completo))[-1],
  row.names = NULL
)
tabla_conteos_NAS
```

